In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,3])

print(arr)
type(arr)

[1 2 3]


numpy.ndarray

# Dimensions in Arrays

# 1D Array

In [16]:
print(arr.ndim)

1


# 2D Array

In [17]:

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a.ndim

2

# 3D Array

In [19]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
b.ndim

3

# Shape of an Array
* The shape of an array is the number of element in each dimension

# Reshaping of arrays

* reshaping means changing the shape of an array
* the shape of an array is the number of elements in each dimension
* By reshaping we can add or remove dimensions or change number of elements in each dimension
* We can reshape array into any Shape As long as the elements required for reshaping  are equal in both shapes. 

In [26]:
#Reshape From 1-D to 2-D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
arr.shape


(12,)

In [30]:
newarr.shape

(4, 3)

In [33]:
new_arr2 = arr.reshape(2,3,2)
new_arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [34]:
new_arr2.shape

(2, 3, 2)

# Flattening the arrays
* flattening array means converting a Multidimensional array into 1-D Array
* We can use reshape(-1) to do this.

In [38]:
twoD_array = np.array([[1,2,3],[4,5,6]])
flatten_array = twoD_array.reshape(-1)

In [39]:
flatten_array

array([1, 2, 3, 4, 5, 6])

In [40]:
flatten_array.shape

(6,)

# Indexing

In [41]:
In = np.array([3,4,5,6])
In

array([3, 4, 5, 6])

In [42]:
In.ndim

1

In [43]:
In[0]

3

In [44]:
In[2]+In[0]

8

In [45]:
#2-D array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
#Access the elements from 2nd row and 5th column
b[1,4]

10

# Iterating Array

In [47]:
arr = np.array([1,2,3,4,5])

In [48]:
for i in arr:
    print(i)

1
2
3
4
5


In [50]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [51]:
for j in arr2:
    print(j)

[1 2 3]
[4 5 6]


In [52]:
for j in arr2:
    for b in j:
        print(b)

1
2
3
4
5
6


# Slicing arrays
* slicing in python means taking elements from one index to another given index
* we pass slice instead of index like this[start:end]

In [53]:
arr2 = np.array([[1,2,3,6,5,4],[4,5,6,2,7,9]])

In [57]:
arr2[1,1:5]

array([5, 6])

# Sorting an Array

In [58]:
arr2 = np.array([1,2,3,6,5,4,0])
np.sort(arr2)

array([0, 1, 2, 3, 4, 5, 6])

In [60]:
arr3 = np.array(['mango','orange','apple','bananna'])
np.sort(arr3)

array(['apple', 'bananna', 'mango', 'orange'], dtype='<U7')